# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fast-ai-course-1',
                'doc_host': 'https://kerembaskaya.github.io',
                'git_url': 'https://github.com/kerembaskaya/fast-ai-course-1',
                'lib_path': 'fast_ai_course_1'},
  'syms': {'fast_ai_course_1.core': {'fast_ai_course_1.core.foo': ('core.html#foo', 'fast_ai_course_1/core.py')}}}
